# Language Settings
#
# Available locale: en, fr, pt, zh_cn, hu, de
#
# If you want to create your own, the file name must match the locale name.
# Example:
# - Create es.yml in locale/
# - Set locale: es
#
locale: en

# Protection suit settings
#
# enabled: true or false
# reduction: A 0.5 reduction is a 50% reduction in damage. 0.6 is 60% and so on...
#
beeprotectionsuit:
  enabled: true
  reduction: 0.50

# Bee healing settings
#
# removeanger: remove anger from bees when they are healed?
#
healing:
  removeanger: true

# Beehive upgrade settings
#
#   maximumSize: maximum number of bees a beehive can be upgraded to
#
beehiveupgrade:
  maximumpopulation: 9